spring:
  application:
    name: football-live-platform
  datasource:
    url: jdbc:postgresql://localhost:5432/flp_db
    username: flp_user
    password: flp_pwd

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: false

  jpa:
    hibernate:
      ddl-auto: validate