CREATE TABLE country (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(100) NOT NULL,
    iso_code CHAR(2) NOT NULL,

    CONSTRAINT pk_country PRIMARY KEY (id),
    CONSTRAINT uk_country_name UNIQUE (name),
    CONSTRAINT uk_country_iso_code UNIQUE (iso_code)
);