CREATE TABLE championship (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(150) NOT NULL,
    country_id BIGINT NOT NULL,

    CONSTRAINT pk_championship PRIMARY KEY (id),
    CONSTRAINT uk_championship_name_country UNIQUE (name, country_id),
    CONSTRAINT fk_championship_country
        FOREIGN KEY (country_id)
        REFERENCES country (id)
);

CREATE TABLE championship_season (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    championship_id BIGINT NOT NULL,
    year SMALLINT NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    status VARCHAR(20) NOT NULL,

    CONSTRAINT pk_championship_season PRIMARY KEY (id),
    CONSTRAINT uk_championship_season_year UNIQUE (championship_id, year),
    CONSTRAINT fk_championship_season_championship
        FOREIGN KEY (championship_id)
        REFERENCES championship (id),
    CONSTRAINT ck_championship_season_dates CHECK (end_date >= start_date)
);