CREATE TABLE stadium (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(150) NOT NULL,
    city VARCHAR(100) NOT NULL,
    state VARCHAR(100),
    country_id BIGINT NOT NULL,
    capacity INTEGER,

    CONSTRAINT pk_stadium PRIMARY KEY (id),
    CONSTRAINT uk_stadium_name_city_country UNIQUE (name, city, country_id),
    CONSTRAINT fk_stadium_country
        FOREIGN KEY (country_id)
        REFERENCES country (id),
    CONSTRAINT ck_stadium_capacity CHECK (capacity IS NULL OR capacity > 0)
);