CREATE TABLE club (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(150) NOT NULL,
    country_id BIGINT NOT NULL,
    state VARCHAR(100),
    stadium_id BIGINT NOT NULL,
    founded_at DATE,

    CONSTRAINT pk_club PRIMARY KEY (id),
    CONSTRAINT uk_club_name_country UNIQUE (name, country_id),
    CONSTRAINT fk_club_country
        FOREIGN KEY (country_id)
        REFERENCES country (id),
    CONSTRAINT fk_club_stadium
        FOREIGN KEY (stadium_id)
        REFERENCES stadium (id)
);

CREATE TABLE championship_season_club (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    championship_season_id BIGINT NOT NULL,
    club_id BIGINT NOT NULL,
    registered_at TIMESTAMP WITH TIME ZONE NOT NULL,
    status VARCHAR(20) NOT NULL,

    CONSTRAINT pk_championship_season_club PRIMARY KEY (id),
    CONSTRAINT uk_championship_season_club UNIQUE (championship_season_id, club_id),
    CONSTRAINT uk_championship_season_club_id_season UNIQUE (id, championship_season_id),
    CONSTRAINT fk_championship_season_club_season
        FOREIGN KEY (championship_season_id)
        REFERENCES championship_season (id),
    CONSTRAINT fk_championship_season_club_club
        FOREIGN KEY (club_id)
        REFERENCES club (id)
);