CREATE TABLE coach (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(150) NOT NULL,
    country_id BIGINT NOT NULL,
    birth_date DATE,

    CONSTRAINT pk_coach PRIMARY KEY (id),
    CONSTRAINT fk_coach_country
        FOREIGN KEY (country_id)
        REFERENCES country (id)
);

CREATE TABLE club_coach (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    club_id BIGINT NOT NULL,
    coach_id BIGINT NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE,

    CONSTRAINT pk_club_coach PRIMARY KEY (id),
    CONSTRAINT fk_club_coach_club
        FOREIGN KEY (club_id)
        REFERENCES club (id),
    CONSTRAINT fk_club_coach_coach
        FOREIGN KEY (coach_id)
        REFERENCES coach (id),
    CONSTRAINT ck_club_coach_dates CHECK (end_date IS NULL OR end_date >= start_date)
);

CREATE TABLE player (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(150) NOT NULL,
    country_id BIGINT NOT NULL,
    birth_date DATE NOT NULL,
    preferred_foot CHAR(1) NOT NULL,

    CONSTRAINT pk_player PRIMARY KEY (id),
    CONSTRAINT fk_player_country
        FOREIGN KEY (country_id)
        REFERENCES country (id),
    CONSTRAINT ck_player_preferred_foot CHECK (preferred_foot IN ('L', 'R', 'B'))
);