CREATE TABLE squad_membership (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    championship_season_id BIGINT NOT NULL,
    championship_season_club_id BIGINT NOT NULL,
    player_id BIGINT NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE,

    CONSTRAINT pk_squad_membership PRIMARY KEY (id),
    CONSTRAINT uk_squad_membership_club_player UNIQUE (championship_season_club_id, player_id),
    CONSTRAINT uk_squad_membership_id_club UNIQUE (id, championship_season_club_id),
    CONSTRAINT fk_squad_membership_season_club
        FOREIGN KEY (championship_season_club_id, championship_season_id)
        REFERENCES championship_season_club (id, championship_season_id),
    CONSTRAINT fk_squad_membership_player
        FOREIGN KEY (player_id)
        REFERENCES player (id),
    CONSTRAINT ck_squad_membership_dates CHECK (end_date IS NULL OR end_date >= start_date),
    CONSTRAINT ex_squad_membership_player_Season_period
        EXCLUDE USING gist (
            championship_season_id WITH =,
            player_id WITH =,
            daterange(
                start_date,
                COALESCE(end_date, 'infinity'::date),
                '[]'
            ) WITH &&
        )
);

CREATE TABLE squad_membership_assignment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    squad_membership_id BIGINT NOT NULL,
    championship_season_club_id BIGINT NOT NULL,
    shirt_number SMALLINT NOT NULL,
    position VARCHAR(30) NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE,

    CONSTRAINT pk_squad_membership_assignment PRIMARY KEY (id),
    CONSTRAINT fk_squad_membership_assignment_membership
        FOREIGN KEY (squad_membership_id, championship_season_club_id)
        REFERENCES squad_membership (id, championship_season_club_id),
    CONSTRAINT ck_squad_membership_assignment_shirt_number CHECK (shirt_number BETWEEN 1 AND 99),
    CONSTRAINT ck_squad_membership_assignment_dates CHECK (end_date IS NULL OR end_date >= start_date),
    CONSTRAINT ex_squad_membership_assignment_period
        EXCLUDE USING gist (
            squad_membership_id WITH =,
            daterange(
                start_date,
                COALESCE(end_date, 'infinity'::date),
                '[]'
            ) WITH &&
        ),
    CONSTRAINT ex_squad_membership_assignment_shirt_number_period
        EXCLUDE USING gist (
            championship_season_club_id WITH =,
            shirt_number WITH =,
            daterange(
                start_date,
                COALESCE(end_date, 'infinity'::date),
                '[]'
            ) WITH &&
        )
);