CREATE TABLE game (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    championship_season_id BIGINT NOT NULL,
    scheduled_at TIMESTAMP WITH TIME ZONE NOT NULL,
    home_championship_season_club_id BIGINT NOT NULL,
    away_championship_season_club_id BIGINT NOT NULL,
    stadium_id BIGINT NOT NULL,
    status VARCHAR(20) NOT NULL,
    home_score SMALLINT,
    away_score SMALLINT,

    CONSTRAINT pk_game PRIMARY KEY (id),
    CONSTRAINT fk_game_home_season_club
        FOREIGN KEY (home_championship_season_club_id, championship_season_id)
        REFERENCES championship_season_club (id, championship_season_id),
    CONSTRAINT fk_game_away_season_club
        FOREIGN KEY (away_championship_season_club_id, championship_season_id)
        REFERENCES championship_season_club (id, championship_season_id),
    CONSTRAINT fk_game_stadium
        FOREIGN KEY (stadium_id)
        REFERENCES stadium (id),
    CONSTRAINT ck_game_distinct_clubs
        CHECK (home_championship_season_club_id <> away_championship_season_club_id),
    CONSTRAINT ck_game_scores
        CHECK (
            (home_score IS NULL OR home_score >= 0)
            AND
            (away_score IS NULL OR away_score >= 0)
        )
);